// Fill out your copyright notice in the Description page of Project Settings.


#include "Character/DFCharacter.h"

#include "EnhancedInputComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"

// Sets default values
ADFCharacter::ADFCharacter()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = false;
	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->bUsePawnControlRotation = false;
	SpringArm->SetupAttachment(GetRootComponent());

	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("CameraComponent"));
	Camera->SetupAttachment(SpringArm);
}

// Called when the game starts or when spawned
void ADFCharacter::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called to bind functionality to input
void ADFCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	UEnhancedInputComponent* EnhancedInputComponent = Cast<UEnhancedInputComponent>(InputComponent);
	
	if (!EnhancedInputComponent) return;

	EnhancedInputComponent->BindAction(
		MoveAction,
		ETriggerEvent::Triggered,
		this,
		&ADFCharacter::Move
	);
	
	EnhancedInputComponent->BindAction(
		LookAction,
		ETriggerEvent::Triggered,
		this,
		&ADFCharacter::Look
	);
	
	EnhancedInputComponent->BindAction(
		SprintAction,
		ETriggerEvent::Triggered,
	this,
		&ADFCharacter::Sprint
	);
	
}

void ADFCharacter::Move(const FInputActionValue& Value)
{
	AController* PlayerController = GetController();

	if (!ensure(PlayerController)) return;

	const FVector2D MoveValue = Value.Get<FVector2D>();
	const FRotator MovementRotation(0.f, PlayerController->GetControlRotation().Yaw, 0.0f);

	FVector MovementDirection = FVector::ZeroVector;

	if (MoveValue.X != 0.0f)
	{
		MovementDirection = MovementRotation.RotateVector(FVector::ForwardVector);
		AddMovementInput(MovementDirection, MoveValue.X);
	}

	if (MoveValue.Y != 0.0f)
	{
		MovementDirection = MovementRotation.RotateVector(FVector::RightVector);
		AddMovementInput(MovementDirection, MoveValue.Y);
	}

	// üî• Ïù¥Îèô Î∞©Ìñ•Ïù¥ 0Ïù¥ ÏïÑÎãàÎùºÎ©¥ Ï∫êÎ¶≠ÌÑ∞ ÌöåÏ†Ñ Ï†ÅÏö© (Î∂ÄÎìúÎüΩÍ≤å)
	if (!MovementDirection.IsNearlyZero())
	{
		FRotator TargetRotation = MovementDirection.Rotation();
		FRotator NewRotation = FMath::RInterpTo(GetActorRotation(), TargetRotation, GetWorld()->GetDeltaSeconds(), 10.0f);
		SetActorRotation(FRotator(0.f, NewRotation.Yaw, 0.f)); // Yaw ÌöåÏ†ÑÎßå Ï†ÅÏö©
	}
}

void ADFCharacter::Sprint(const FInputActionValue& Value)
{
}

void ADFCharacter::Look(const FInputActionValue& Value)
{
	const FVector2D LookValue = Value.Get<FVector2D>();

	if (!SpringArm) return; // Ïä§ÌîÑÎßÅÏïîÏù¥ ÏóÜÏúºÎ©¥ Ïã§Ìñâ Ïïà Ìï®

	FRotator CurrentRotation = SpringArm->GetRelativeRotation();

	// XÏ∂ï(Yaw): Ï¢åÏö∞ ÌöåÏ†Ñ (Ï∫êÎ¶≠ÌÑ∞ ÌöåÏ†ÑÍ≥º Î∂ÑÎ¶¨)
	if (LookValue.X != 0.0f)
	{
		CurrentRotation.Yaw += LookValue.X;
	}

	// YÏ∂ï(Pitch): ÏúÑÏïÑÎûò ÌöåÏ†Ñ (Ïπ¥Î©îÎùº ÏúÑÏïÑÎûò ÏõÄÏßÅÏûÑ)
	if (LookValue.Y != 0.0f)
	{
		CurrentRotation.Pitch = FMath::Clamp(CurrentRotation.Pitch + LookValue.Y, -80.0f, 80.0f); // ÏÉÅÌïò Ï†úÌïú
	}

	SpringArm->SetRelativeRotation(CurrentRotation);
}
void ADFCharacter::Grab(const FInputActionValue& Value)
{
}

void ADFCharacter::Kick(const FInputActionValue& Value)
{
}

void ADFCharacter::StartJump(const FInputActionValue& Value)
{
	Jump();
}